# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69ce03a7332959150a434c93e05c6f58"
name = "rahul-remix-2"
handle = "rahul-remix-3"
application_url = "https://such-reflection-brought-cycles.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "node-test-conative.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://such-reflection-brought-cycles.trycloudflare.com/auth/callback",
  "https://such-reflection-brought-cycles.trycloudflare.com/auth/shopify/callback",
  "https://such-reflection-brought-cycles.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
